### ISSUE TITLE
Fast Whisper Server on Hugging Face Docker Space

### ISSUE THREAD

**Issue by rrg92** [fedirz/faster-whisper-server#27]
**For those who tried to deploy Docker on Hugging Face**

Hello, I tried to deploy the server in a Docker Space on Hugging Face, but I had difficulties because on Hugging Face, the container runs with user 1000.

So, I created a new Dockerfile for Hugging Face.

I put it here: https://huggingface.co/spaces/Iatalking/fast-whisper-server

Has anyone done it differently?

@fedirz  Do you think it's worth submitting a PR that adds a new Dockerfile exclusively for deploying on Hugging Face?

**Comment by fedirz** [comment]
Hey, I was working on adding it in a couple of weeks ago but decided not to proceed further because HF requires you to put the Docker Space configuration within a `README.md` file, which I didn't want to do. I'll end up creating a separate repo at some point just for the space. Thanks for creating an issue and sharing your code, I'll use it as a reference when working on it again!

I'll keep this issue open for now until I create the space.

**Comment by fedirz** [comment]
Actually

**Comment by rrg92** [comment]
Thanks!
